### PR TITLE
New code for arm and elevator, and (Hopefully) a basic class for responding to the vision inputs

### PR DESCRIPTION
**Pull request by Wynter-Tau**
The bit for responding to vision inputs is called seekermode, it needs to be tested

### CODE REVIEW

**Comment by BUNN1E5** [comment]
Is this code confirmed to work (not including the seeker code)

**Review by BUNN1E5 — CHANGES_REQUESTED** [review]
Why PIDSparkMaxGroup instead of MotorGroup in Robot.java and SeekerMode.java? Is there a function in PIDSparkMaxGroup that isn't in MotorGroup? If so it might be better to change the interface to reflect that because you lose the benefits of using an Interface otherwise.

**Comment by Wynter-Tau** [comment]
The drive and elevator code is confirmed to work, the arm code worked but then changes were made and it needs retuning, we'll hopefully be doing that today, and PIDSpakMaxGroup does have a function MotorGroup doesn't have, as they have Position control via PID, as not all motorcontrollers have that, I choose not to add that to the MotorGroup interface

**Comment by BUNN1E5** [comment]
Ok looks good

**Pull request merged**
